// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cksbobuqhkgbjccmrciy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrc2JvYnVxaGtnYmpjY21yY2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0ODM5NjgsImV4cCI6MjA1MzA1OTk2OH0.50or-K0BGnVM731GTsmvsaYMQUl5-B5760Dkc3JKpRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);